fix v0.0.13

diff --git a/.github/workflows/c-cpp.yml b/.github/workflows/c-cpp.yml
--- a/.github/workflows/c-cpp.yml
+++ b/.github/workflows/c-cpp.yml
@@ -59,13 +59,26 @@ jobs:
           echo "CMake version: $(cmake --version)"
           echo "GCC version: $(gcc --version)"
           echo "Looking for Qt6 CMake files in /mingw64/lib/cmake/Qt6..."
-          ls -Al /mingw64/lib/cmake/Qt6 || echo "Qt6 CMake directory not found or empty."
-          ls -Al /mingw64/bin || echo "mingw64 bin is empty"
+          # ls -Al /mingw64/lib/cmake/Qt6 || echo "Qt6 CMake directory not found or empty."
           
-          export MINGW_COMPILER_BIN_DIR="/mingw64/bin"
-          echo "MINGW_COMPILER_BIN_DIR is set to: $MINGW_COMPILER_BIN_DIR"
+          echo "CMAKE_PREFIX_PATH is set to: $CMAKE_PREFIX_PATH"
           
           ./build.sh --clean
+          
+          echo "PATH: $PATH"
+          # ls -l /mingw64/bin/windeployqt*
+
+          which windeployqt6
+          
+          mkdir ./build/Release
+          
+          cp ./build/bin/ITools.exe ./build/Release
+          
+          windeployqt6 --verbose 2 --dir "./build/Release" "./build/Release/ITools.exe"
+          
+          echo "--- Listing deployment directory contents ---"
+          ls -alh ./build/Release
+
         env:
           MINGW_COMPILER_BIN_DIR: /mingw64/bin
           CMAKE_DOTNET_TARGET_FRAMEWORK: ${{ env.DOTNET_ROOT }}/packs/Microsoft.NETCore.App.Host.win-x64/9.0.5/runtimes/win-x64/native
