Adds a chache ability

diff --git a/.github/workflows/vcpkg-build-cache.yml b/.github/workflows/vcpkg-build-cache.yml
--- a/.github/workflows/vcpkg-build-cache.yml
+++ b/.github/workflows/vcpkg-build-cache.yml
@@ -63,74 +63,79 @@ jobs:
         run: ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh
         shell: bash
 
+      - name: Cache Vcpkg Asset Downloads
+        uses: actions/cache@v4
+        with:
+          path: |
+            ${{ github.workspace }}/vcpkg/downloads
+            ${{ github.workspace }}/vcpkg/toolsrc
+          key: ${{ runner.os }}-${{ matrix.build_type }}-vcpkg-assets-${{ hashFiles('it-tools-editor/vcpkg.json') }}
+          restore-keys: |
+            ${{ runner.os }}-vcpkg-assets-
+
+      - name: Configure NuGet for GitHub Packages
+        env:
+          USERNAME: ${{ github.repository_owner }}
+          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
+        shell: ${{ matrix.cmake_shell }}
+        run: |
+          if ("${{ runner.os }}" -eq "Windows") {
+            $nugetConfigPath = Join-Path $env:APPDATA "NuGet\NuGet.Config"
+            $nugetConfigContent = @"
+            <?xml version="1.0" encoding="utf-8"?>
+            <configuration>
+              <packageSources>
+                <clear />
+                <add key="GitHubPackages" value="https://nuget.pkg.github.com/$env:USERNAME/index.json" />
+              </packageSources>
+              <packageSourceCredentials>
+                <GitHubPackages>
+                  <add key="Username" value="$env:USERNAME" />
+                  <add key="ClearTextPassword" value="$env:GH_PACKAGES_TOKEN" />
+                </GitHubPackages>
+              </packageSourceCredentials>
+            </configuration>
+            "@
+            New-Item -ItemType Directory -Force -Path (Split-Path $nugetConfigPath)
+            $nugetConfigContent | Out-File $nugetConfigPath
+            Write-Host "Created NuGet.Config at $nugetConfigPath"
+          } else {
+            mkdir -p ~/.nuget/NuGet
+            echo '<?xml version="1.0" encoding="utf-8"?>' > ~/.nuget/NuGet/NuGet.Config
+            echo '<configuration>' >> ~/.nuget/NuGet/NuGet.Config
+            echo '  <packageSources>' >> ~/.nuget/NuGet/NuGet.Config
+            echo '    <clear />' >> ~/.nuget/NuGet/NuGet.Config
+            echo '    <add key="GitHubPackages" value="https://nuget.pkg.github.com/'"${{ env.USERNAME }}"'/index.json" />' >> ~/.nuget/NuGet/NuGet.Config
+            echo '  </packageSources>' >> ~/.nuget/NuGet/NuGet.Config
+            echo '  <packageSourceCredentials>' >> ~/.nuget/NuGet/NuGet.Config
+            echo '    <GitHubPackages>' >> ~/.nuget/NuGet/NuGet.Config
+            echo '      <add key="Username" value="'"${{ env.USERNAME }}"'" />' >> ~/.nuget/NuGet/NuGet.Config
+            echo '      <add key="ClearTextPassword" value="'"${{ env.GH_PACKAGES_TOKEN }}"'" />' >> ~/.nuget/NuGet/NuGet.Config
+            echo '    </GitHubPackages>' >> ~/.nuget/NuGet/NuGet.Config
+            echo '  </packageSourceCredentials>' >> ~/.nuget/NuGet/NuGet.Config
+            echo '</configuration>' >> ~/.nuget/NuGet/NuGet.Config
+            echo "Created NuGet.Config at ~/.nuget/NuGet/NuGet.Config"
+          }
+      - name: Set NuGet API Key for GitHub Packages
+        env:
+          VCPKG_EXE: ${{ github.workspace }}/vcpkg/vcpkg.exe
+          GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
+        run: |
+          if ("${{ runner.os }}" -eq "Windows") {
+            $nuget_path = & "${{ env.VCPKG_EXE }}" fetch nuget | Select-String -Pattern '\S+\.exe$' | ForEach-Object { $_.Matches[0].Value }
+            if (-not $nuget_path) { Write-Error "Failed to get nuget.exe path."; exit 1 }
+            & "$nuget_path" setapikey "${{ env.GH_PACKAGES_TOKEN }}" -Source "GitHubPackages" -NonInteractive 2>&1 | Write-Host
+          
+            Write-Host "API Key for GitHubPackages set successfully."
+          } else {
+            NUGET_PATH=$(mono "${{ env.VCPKG_EXE }}" fetch nuget | tail -n 1)
+            if [ -z "$NUGET_PATH" ]; then echo "Failed to get nuget.exe path." && exit 1; fi
+            mono "$NUGET_PATH" setapikey "${{ env.GH_PACKAGES_TOKEN }}" -Source "GitHubPackages" -NonInteractive 2>&1 | cat
+          }
+
 #jobs:
 #  build:
-#    strategy:
-#      fail-fast: false
-#      matrix:
-#        os: [ windows-latest, ubuntu-latest, macos-latest ]
-#        build_type: [ Debug, Release ]
-#        include:
-#          - os: windows-latest
-#            vcpkg_triplet: x64-windows # <--- CHANGED FROM x64-mingw-dynamic
-#            cmake_shell: pwsh
-#            cmake_line_continuation: '`'
-#          - os: ubuntu-latest
-#            vcpkg_triplet: x64-linux
-#            cmake_shell: bash
-#            cmake_line_continuation: '\'
-#          - os: macos-latest
-#            vcpkg_triplet: x64-osx
-#            cmake_shell: bash
-#            cmake_line_continuation: '\'
-#    runs-on: ${{ matrix.os }}
-#    permissions:
-#      contents: read
-#      packages: write
 #    steps:
-#      - name: Checkout Repository
-#        uses: actions/checkout@v4
-#        with:
-#          submodules: true
-#          path: it-tools-editor
-#          fetch-depth: 0
-#
-#      # MODIFIED/CONDITIONAL STEP: Set up MSYS2 with Build Tools (Windows Only)
-#      # This step is now only conditionally needed if your *other* project dependencies
-#      # (outside of vcpkg for Qt) still strictly require MSYS2/MinGW tools.
-#      # If your project only needs CMake, Ninja, and Visual Studio for Windows, you can REMOVE THIS STEP ENTIRELY.
-#      - name: Set up MSYS2 with Build Tools (Windows Only, if needed)
-#        if: runner.os == 'Windows' && matrix.vcpkg_triplet == 'x64-mingw-dynamic' # Only run if MinGW is used
-#        uses: msys2/setup-msys2@v2
-#        with:
-#          msys2-architecture: x86_64
-#          update: true
-#          install: >
-#            mingw-w64-x86_64-toolchain
-#            git
-#            ninja
-#          path-type: minimal
-#          msystem: MINGW64
-#      # IMPORTANT: If you switch to x64-windows triplet for Windows,
-#      # you will NOT need the MSYS2 setup step unless your *application*
-#      # (not its vcpkg dependencies) relies on specific MSYS2 tools.
-#      # The 'windows-latest' runner comes with Visual Studio and basic Git/CMake pre-installed.
-#      - name: Clone Vcpkg Repository
-#        if: ${{ github.workspace }}/it-tools-editor/vcpkg == '' || !contains(github.workspace, 'it-tools-editor/vcpkg')
-#        uses: actions/checkout@v4
-#        with:
-#          repository: microsoft/vcpkg
-#          ref: master
-#          path: vcpkg
-#          fetch-depth: 0
-#      - name: Bootstrap Vcpkg
-#        shell: ${{ matrix.cmake_shell }}
-#        run: |
-#          if ("${{ runner.os }}" -eq "Windows") {
-#            ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.bat
-#          } else {
-#            ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh
-#          }
 #
 #      - name: Cache Vcpkg Asset Downloads
 #        uses: actions/cache@v4
